#!/usr/bin/env bash

cwd=$(pwd)

find . -type d -name .git | while read -r dir
do
	cd $(dirname $dir);
	echo -e "\033[44m$(pwd)\033[0m"
	branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')
	git pull origin $branch
	cd $cwd
done
